export const coffees = [
  {
    name: "Expresso Tradicional",
    type: "Tradicional",
    description: "O tradicional café feito com água quente e grãos moídos",
    price: "9,90",
    currency: "R$",
    image: "Image.png",
  },
  {
    name: "Expresso Americano",
    type: "Tradicional",
    description: "Expresso diluído, menos intenso que o tradicional",
    price: "9,90",
    currency: "R$",
    image: "cafe.png",
  },
  {
    name: "Expresso Cremoso",
    type: "Tradicional",
    description: "Café expresso tradicional com espuma cremosa",
    price: "9,90",
    currency: "R$",
    image: "cremeso.png",
  },
  {
    name: "Expresso Gelado",
    type: "Tradicional, Gelado",
    description: "Bebida preparada com café expresso e cubos de gelo",
    price: "9,90",
    currency: "R$",
    image: "CaféGelado.png",
  },
  {
    name: "Café com Leite",
    type: "Tradicional, Com Leite",
    description: "Meia a meio de expresso tradicional com leite vaporizado",
    price: "9,90",
    currency: "R$",
    image: "CafécomLeite.png",
  },
  {
    name: "Latte",
    type: "Tradicional, Com Leite",
    description:
      "Uma dose de café expresso com o dobro de leite e espuma cremosa",
    price: "9,90",
    currency: "R$",
    image: "Latte.png",
  },
  {
    name: "Capuccino",
    type: "Tradicional, Com Leite",
    description:
      "Bebida com canela feita de doses iguais de café, leite e espuma",
    price: "9,90",
    currency: "R$",
    image: "Capuccino.png",
  },
  {
    name: "Macchiato",
    type: "Tradicional, Com Leite",
    description:
      "Café expresso misturado com um pouco de leite quente e espuma",
    price: "9,90",
    currency: "R$",
    image: "Macchiato.png",
  },
  {
    name: "Mocaccino",
    type: "Tradicional, Com Leite",
    description: "Café expresso com calda de chocolate, pouco leite e espuma",
    price: "9,90",
    currency: "R$",
    image: "Mochaccino.png",
  },
  {
    name: "Chocolate Quente",
    type: "Especial, Com Leite",
    description:
      "Bebida feita com chocolate dissolvido no leite quente e espuma",
    price: "9,90",
    currency: "R$",
    image: "ChocolateQuente.png",
  },
  {
    name: "Cubano",
    type: "Especial, Alcoólico, Gelado",
    description:
      "Drink gelado de café expresso com rum, creme de leite e hortelã",
    price: "9,90",
    currency: "R$",
    image: "Cubano.png",
  },
  {
    name: "Havaiano",
    type: "Especial",
    description: "Bebida adocicada preparada com café e leite de coco",
    price: "9,90",
    currency: "R$",
    image: "Havaiano.png",
  },
  {
    name: "Árabe",
    type: "Especial",
    description: "Bebida preparada com grãos de café árabe e especiarias",
    price: "9,90",
    currency: "R$",
    image: "Árabe.png",
  },
  {
    name: "Irlandês",
    type: "Especial, Alcoólico",
    description: "Bebida a base de café, uísque irlandês, açúcar e chantilly",
    price: "9,90",
    currency: "R$",
    image: "Irlandês.png",
  },
];
