export const coffees = [
  {
    id: 1,
    name: "Expresso Tradicional",
    type: "Tradicional",
    description: "O tradicional café feito com água quente e grãos moídos",
    price: 5.00,
    currency: "R$",
    image: "Image.png",
  },
  {
    id: 2,
    name: "Expresso Americano",
    type: "Tradicional",
    description: "Expresso diluído, menos intenso que o tradicional",
    price: 6.00,
    currency: "R$",
    image: "cafe.png",
  },
  {
    id: 3,
    name: "Expresso Cremoso",
    type: "Tradicional",
    description: "Café expresso tradicional com espuma cremosa",
    price: 7.00,
    currency: "R$",
    image: "cremeso.png",
  },
  {
    id: 4,
    name: "Expresso Gelado",
    type: "Tradicional, Gelado",
    description: "Bebida preparada com café expresso e cubos de gelo",
    price: 8.00,
    currency: "R$",
    image: "CaféGelado.png",
  },
  {
    id: 5,
    name: "Café com Leite",
    type: "Tradicional, Com Leite",
    description: "Meia a meio de expresso tradicional com leite vaporizado",
    price: 6.50,
    currency: "R$",
    image: "CafécomLeite.png",
  },
  {
    id: 6,
    name: "Latte",
    type: "Tradicional, Com Leite",
    description: "Uma dose de café expresso com o dobro de leite e espuma cremosa",
    price: 7.50,
    currency: "R$",
    image: "Latte.png",
  },
  {
    id: 7,
    name: "Capuccino",
    type: "Tradicional, Com Leite",
    description: "Bebida com canela feita de doses iguais de café, leite e espuma",
    price: 8.00,
    currency: "R$",
    image: "Capuccino.png",
  },
  {
    id: 8,
    name: "Macchiato",
    type: "Tradicional, Com Leite",
    description: "Café expresso misturado com um pouco de leite quente e espuma",
    price: 7.00,
    currency: "R$",
    image: "Macchiato.png",
  },
  {
    id: 9,
    name: "Mocaccino",
    type: "Tradicional, Com Leite",
    description: "Café expresso com calda de chocolate, pouco leite e espuma",
    price: 8.50,
    currency: "R$",
    image: "Mochaccino.png",
  },
  {
    id: 10,
    name: "Chocolate Quente",
    type: "Especial, Com Leite",
    description: "Bebida feita com chocolate dissolvido no leite quente e espuma",
    price: 9.00,
    currency: "R$",
    image: "ChocolateQuente.png",
  },
  {
    id: 11,
    name: "Cubano",
    type: "Especial, Alcoólico, Gelado",
    description: "Drink gelado de café expresso com rum, creme de leite e hortelã",
    price: 10.00,
    currency: "R$",
    image: "Cubano.png",
  },
  {
    id: 12,
    name: "Havaiano",
    type: "Especial",
    description: "Bebida adocicada preparada com café e leite de coco",
    price: 9.50,
    currency: "R$",
    image: "Havaiano.png",
  },
  {
    id: 13,
    name: "Árabe",
    type: "Especial",
    description: "Bebida preparada com grãos de café árabe e especiarias",
    price: 9.00,
    currency: "R$",
    image: "Árabe.png",
  },
  {
    id: 14,
    name: "Irlandês",
    type: "Especial, Alcoólico",
    description: "Bebida a base de café, uísque irlandês, açúcar e chantilly",
    price: 11.00,
    currency: "R$",
    image: "Irlandês.png",
  },
];
